name: pplref
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.5
  - numpy=1.11.2
  - twobitreader
  - bedtools=2.26.0
  - grep
  - p7zip
  - ucsc-fatotwobit
  - ucsc-twobittofa
  - ucsc-twobitinfo
  - salmon=0.8.2
  - ucsc-chainfilter
  - ucsc-chainnet
  - ucsc-chainprenet
  - ucsc-chainsort
  - ucsc-chainsplit
  - ucsc-chainstitchid
  - ucsc-chainswap
  - ucsc-netsyntenic
  - ucsc-nettobed
  - ucsc-netchainsubset
  - ucsc-chaintoaxt
  - pandas=0.19
  - pytables=3.2.3.1
  - scipy=0.18.*
  - scikit-learn=0.18
  - statsmodels=0.6.1
  - samtools=1.3.*
  - htslib=1.3.*
  - bitarray
  - bowtie2