name: pplref
channels:
  - bioconda
dependencies:
  - python=3.5
  - numpy=1.11.2
  - twobitreader
  - bedtools=2.26.0
  - grep
  - p7zip
  - ucsc-fatotwobit
  - salmon=0.7.2
  - ucsc-chainfilter
  - ucsc-chainnet
  - ucsc-chainprenet
  - ucsc-chainsort
  - ucsc-chainsplit
  - ucsc-chainstitchid
  - ucsc-chainswap
  - ucsc-netsyntenic
  - ucsc-nettobed
  - ucsc-netchainsubset
  - pandas=0.19
  - pytables=3.2.3.1